### ISSUE TITLE
Feature request: support non-text inputs

### ISSUE THREAD

**Issue by romgrk** [acoyfellow/FormSync#1]
Hi there,

This is awesome, I was in need of something like this yesterday!
However, I also need to preserve the state of some radio/checkbox/select fields. Do you plan on having those stored as well?

**Comment by romgrk** [comment]
Nevermind, I didn't read the readme carefully :)

**Comment by acoyfellow** [comment]
I haven't implemented select fields yet, but I definitely will. Thanks for the note!

**Comment by acoyfellow** [comment]
@romgrk - Just added `<select>` field input -- https://jsfiddle.net/acoyfellow/2se2rLq2/
